/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APIError
 */
export interface APIError {
    /**
     * Short description of the error
     * @type {string}
     * @memberof APIError
     */
    'message': string;
    /**
     * Long description of the error
     * @type {string}
     * @memberof APIError
     */
    'description': string;
    /**
     * Details of the error
     * @type {Array<string>}
     * @memberof APIError
     */
    'details': Array<string>;
}

