/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyContactInfo } from './company-contact-info';
// May contain unused imports in some cases
// @ts-ignore
import { Invoice } from './invoice';

/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * ID of the company
     * @type {string}
     * @memberof Company
     */
    'id': string;
    /**
     * Account ID to which the company belongs
     * @type {string}
     * @memberof Company
     */
    'accountId': string;
    /**
     * Name of the company
     * @type {string}
     * @memberof Company
     */
    'name': string;
    /**
     * Company tax registration information
     * @type {Array<string>}
     * @memberof Company
     */
    'taxRegistrations': Array<string>;
    /**
     * List of invoices generated for the company
     * @type {Array<Invoice>}
     * @memberof Company
     */
    'invoices': Array<Invoice>;
    /**
     * URL of company logo
     * @type {string}
     * @memberof Company
     */
    'logoURL': string;
    /**
     * Registered postal address of the company
     * @type {string}
     * @memberof Company
     */
    'address': string;
    /**
     * City in which the company exists
     * @type {string}
     * @memberof Company
     */
    'city': string;
    /**
     * State in which the company exists
     * @type {string}
     * @memberof Company
     */
    'state': string;
    /**
     * Country in which the company exists
     * @type {string}
     * @memberof Company
     */
    'country': string;
    /**
     * Contact details of the company
     * @type {Array<CompanyContactInfo>}
     * @memberof Company
     */
    'contactInfo': Array<CompanyContactInfo>;
}

