/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyContactInfo
 */
export interface CompanyContactInfo {
    /**
     * 
     * @type {string}
     * @memberof CompanyContactInfo
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CompanyContactInfo
     */
    'phone': string;
}

