/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Product } from './product';
// May contain unused imports in some cases
// @ts-ignore
import { ProductCompany } from './product-company';

/**
 * @type CreateProductResponseData
 * The newly created product
 * @export
 */
export type CreateProductResponseData = Product;


