/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Company } from './company';
// May contain unused imports in some cases
// @ts-ignore
import { CompanyContactInfo } from './company-contact-info';
// May contain unused imports in some cases
// @ts-ignore
import { Invoice } from './invoice';

/**
 * @type CreateCompanyResponseData
 * The newly created company
 * @export
 */
export type CreateCompanyResponseData = Company;


