/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateProductRequestBody
 */
export interface CreateProductRequestBody {
    /**
     * Name of the product is required
     * @type {string}
     * @memberof CreateProductRequestBody
     */
    'name': string;
    /**
     * description of the product
     * @type {string}
     * @memberof CreateProductRequestBody
     */
    'description'?: string;
    /**
     * HSN of the product
     * @type {string}
     * @memberof CreateProductRequestBody
     */
    'hsn'?: string;
    /**
     * Price of the product
     * @type {number}
     * @memberof CreateProductRequestBody
     */
    'price': number;
    /**
     * Unit of the product
     * @type {string}
     * @memberof CreateProductRequestBody
     */
    'units'?: string;
    /**
     * Metadata allows you to attach arbitrary bits of information to the product. This metadata is searchable. For example: {tags: [\"clothing\", \"male\"]}
     * @type {string}
     * @memberof CreateProductRequestBody
     */
    'metadata'?: string;
}

