/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Client } from './client';
// May contain unused imports in some cases
// @ts-ignore
import { ClientCompany } from './client-company';

/**
 * @type DeleteClientResponseData
 * The deleted client
 * @export
 */
export type DeleteClientResponseData = Client;


