/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InvoiceLineItem
 */
export interface InvoiceLineItem {
    /**
     * ID of the line item
     * @type {string}
     * @memberof InvoiceLineItem
     */
    'id': string;
    /**
     * ID of the associated invoice
     * @type {string}
     * @memberof InvoiceLineItem
     */
    'invoiceId': string;
    /**
     * ID of the associated product or service. If null, the product or service is not associated internally
     * @type {string}
     * @memberof InvoiceLineItem
     */
    'itemId': string;
    /**
     * Type of line item.
     * @type {string}
     * @memberof InvoiceLineItem
     */
    'itemType': InvoiceLineItemItemTypeEnum;
    /**
     * Title of the line item
     * @type {string}
     * @memberof InvoiceLineItem
     */
    'title': string;
    /**
     * Short description of the line item
     * @type {string}
     * @memberof InvoiceLineItem
     */
    'description': string;
    /**
     * Price at which this item was invoiced
     * @type {number}
     * @memberof InvoiceLineItem
     */
    'price': number;
    /**
     * Quantity of the invoiced item
     * @type {number}
     * @memberof InvoiceLineItem
     */
    'quantity': number;
    /**
     * Order in which the item appears in the rendered invoice
     * @type {number}
     * @memberof InvoiceLineItem
     */
    'sortOrder': number;
    /**
     * Any associated metadata when the invoice was created
     * @type {object}
     * @memberof InvoiceLineItem
     */
    'metadata': object;
    /**
     * Timestamp of line item creation
     * @type {string}
     * @memberof InvoiceLineItem
     */
    'createdAt': string;
}

export const InvoiceLineItemItemTypeEnum = {
    Product: 'product'
} as const;

export type InvoiceLineItemItemTypeEnum = typeof InvoiceLineItemItemTypeEnum[keyof typeof InvoiceLineItemItemTypeEnum];


