/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LineItem
 */
export interface LineItem {
    /**
     * ID of the product or service being invoiced
     * @type {string}
     * @memberof LineItem
     */
    'id'?: string;
    /**
     * Title of the item
     * @type {string}
     * @memberof LineItem
     */
    'title': string;
    /**
     * Short item description
     * @type {string}
     * @memberof LineItem
     */
    'description'?: string;
    /**
     * Price of the line item. Must be indicated in lowest denomination of invoice currency.
     * @type {number}
     * @memberof LineItem
     */
    'price': number;
    /**
     * Quantity of the item being invoiced.
     * @type {number}
     * @memberof LineItem
     */
    'quantity': number;
    /**
     * Order in which the item will appear in the rendered invoice.      If not specified, the sort order will be inferred based on its position in      the array of line items
     * @type {number}
     * @memberof LineItem
     */
    'sortOrder'?: number;
    /**
     * Any metadata attached to this line item.
     * @type {object}
     * @memberof LineItem
     */
    'metadata'?: object;
}

