/* tslint:disable */
/* eslint-disable */
/**
 * Invoice Desk API Documentation
 * Official API documentation for Invoice Desk
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCompanyPayload
 */
export interface UpdateCompanyPayload {
    /**
     * $property is required
     * @type {Array<string>}
     * @memberof UpdateCompanyPayload
     */
    'taxRegistrations': Array<string>;
}

